##============================================================================
##  The contents of this file are covered by the Viskores license. See
##  LICENSE.txt for details.
##
##  By contributing to this file, all contributors agree to the Developer
##  Certificate of Origin Version 1.1 (DCO 1.1) as stated in DCO.txt.
##============================================================================

##============================================================================
##  Copyright (c) Kitware, Inc.
##  All rights reserved.
##  See LICENSE.txt for details.
##
##  This software is distributed WITHOUT ANY WARRANTY; without even
##  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##  PURPOSE.  See the above copyright notice for more information.
##============================================================================

# This file is automatically generated by CMake, do not edit.
Viskores_VERSION = 1.0
Viskores_DIR = /builds/gitlab-kitware-sciviz-ci/build/install

Viskores_BUILD_SHARED_LIBS = ON
Viskores_ENABLE_CUDA = OFF
Viskores_ENABLE_KOKKOS = OFF
Viskores_ENABLE_OPENMP = ON
Viskores_ENABLE_TBB = ON
Viskores_ENABLE_LOGGING = ON
Viskores_ENABLE_RENDERING = OFF
Viskores_ENABLE_GL_CONTEXT = 
Viskores_ENABLE_OSMESA_CONTEXT = 
Viskores_ENABLE_EGL_CONTEXT = 
Viskores_ENABLE_MPI = OFF

Viskores_INCLUDE_DIR = $(Viskores_DIR)/include/viskores-1.0
Viskores_INCLUDE_FLAGS = -I$(Viskores_INCLUDE_DIR) -I$(Viskores_INCLUDE_DIR)/viskores/thirdparty/diy/viskoresdiy/include/ -I$(Viskores_INCLUDE_DIR)/viskores/thirdparty/lcl/viskoreslcl/

Viskores_LIB_FLAGS = -L $(Viskores_DIR)/lib \
    -lviskores_source-pv6.0 \
    -lviskores_io-pv6.0 \
    -lviskores_filter_zfp-pv6.0 \
    -lviskores_filter_uncertainty-pv6.0 \
    -lviskores_filter_scalar_topology-pv6.0 \
    -lviskores_filter_resampling-pv6.0 \
    -lviskores_filter_image_processing-pv6.0 \
    -lviskores_filter_flow-pv6.0 \
    -lviskores_filter_field_transform-pv6.0 \
    -lviskores_filter_field_conversion-pv6.0 \
    -lviskores_filter_entity_extraction-pv6.0 \
    -lviskores_filter_density_estimate-pv6.0 \
    -lviskores_filter_geometry_refinement-pv6.0 \
    -lviskores_filter_contour-pv6.0 \
    -lviskores_filter_multi_block-pv6.0 \
    -lviskores_filter_mesh_info-pv6.0 \
    -lviskores_filter_vector_analysis-pv6.0 \
    -lviskores_filter_connected_components-pv6.0 \
    -lviskores_filter_clean_grid-pv6.0 \
    -lviskores_filter_core-pv6.0 \
    -lviskores_worklet-pv6.0 \
    -lviskores_cont_testing-pv6.0 \
    -lviskores_cont-pv6.0 \
    -lviskoresdiympi_nompi
